### ISSUE TITLE
Add an option to play playlist 

### ISSUE THREAD

**Issue by ishamjaglan** [AyushRawal/YTMusic#1]

**Comment by AyushRawal** [comment]
I am working on that. Will be merging it soon. Please wait for a while. 😇

**Comment by ishamjaglan** [comment]
@AyushRawal You made a good app. Really appreciate your efforts.

**Comment by AyushRawal** [comment]
@ishamjaglan  Thanks for the compliment. 😁
I have implemented the requested feature 🎉.
Please take a look.

**Comment by ishamjaglan** [comment]
Still cant get to work it. It shows error
ytmusic.py: error: unrecognized arguments: [then the name of playlist]

**Comment by AyushRawal** [comment]
I have modified the interface a bit. Please refer to the demo.gif in the readme. Also, you can't search for a playlist. To play a playlist you have to provide the URL of the playlist.
![image](https://user-images.githubusercontent.com/32910415/107547461-7b9c5500-6bf3-11eb-80b7-4acfb3f0907a.png)

**Comment by ishamjaglan** [comment]
okay thanks
